name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/reactBle
          git pull origin main
          npm install
          npm run build
          sudo cp -R build/ /var/www/html/react/
          sudo service nginx restart    
